apiVersion: v1
kind: Service
metadata:
  labels:
    app: image-transform-webhook
  name: image-transform-webhook
  namespace: default
spec:
  ports:
    - port: 443
      targetPort: 9443
  selector:
    app: image-transform-webhook
  type: ClusterIP
